export const envObject = {
  BASE_URL: process.env.REACT_APP_BASE_URL,
  API_URL: process.env.REACT_APP_API_URL,

  CLICKUP_CLIENT_ID: process.env.REACT_APP_CLICKUP_CLIENT_ID,
  CLICKUP_REDIRECT_URI: process.env.REACT_APP_CLICKUP_REDIRECT_URI,

  JIRA_CLIENT_ID: process.env.REACT_APP_JIRA_CLIENT_ID,
  JIRA_REDIRECT_URI: process.env.REACT_APP_JIRA_REDIRECT_URI,

  FIREBASE_APIKEY: process.env.REACT_APP_FIREBASE_APIKEY,
  FIREBASE_AUTHDOMAIN: process.env.REACT_APP_FIREBASE_AUTHDOMAIN,
  FIREBASE_PROJECTID: process.env.REACT_APP_FIREBASE_PROJECTID,
  FIREBASE_STORAGEBUCKET: process.env.REACT_APP_FIREBASE_STORAGEBUCKET,
  FIREBASE_MESSAGINGSENDERID: process.env.REACT_APP_FIREBASE_MESSAGINGSENDERID,
  FIREBASE_APPID: process.env.REACT_APP_FIREBASE_APPID,
  FIREBASE_MEASUREMENTID: process.env.REACT_APP_FIREBASE_MEASUREMENTID,
  FIREBASE_VAPIDKEY: process.env.REACT_APP_FIREBASE_VAPIDKEY,

  GOOGLE_CLIENT_ID: process.env.REACT_APP_GOOGLE_CLIENT_ID,
  GOOGLE_REDIRECT_URI: process.env.REACT_APP_GOOGLE_REDIRECT_URI,

  ONE_REDIRECT_URI: process.env.REACT_APP_ONE_REDIRECT_URI,
  ONE_CLIENT_ID: process.env.REACT_APP_ONE_CLIENT_ID,
};
